# Generated by Django 3.2.13 on 2022-05-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_or_issued_date', models.DateTimeField(auto_created=True)),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book_Return_And_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=50)),
                ('date_borrowed', models.DateTimeField()),
                ('late_return', models.CharField(max_length=3)),
                ('borrower_user_details', models.ManyToManyField(blank=True, null=True, to='ty.Borrower_User')),
            ],
        ),
    ]
