# Generated by Django 3.2.13 on 2022-05-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0002_auto_20220505_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_or_issued_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book_return_and_history',
            name='date_borrowed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
