# Generated by Django 3.2.13 on 2022-05-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0003_auto_20220505_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower_user',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
