# Generated by Django 3.2.13 on 2022-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0005_alter_borrower_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
