# Generated by Django 3.2.13 on 2022-05-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0006_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_return_and_history',
            name='borrower_user_details',
        ),
        migrations.AddField(
            model_name='book_return_and_history',
            name='username',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Borrower_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('borrower_user_details', models.ManyToManyField(blank=True, null=True, to='ty.Borrower_User')),
            ],
        ),
    ]
