# Generated by Django 3.2.13 on 2022-05-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0010_auto_20220508_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_return_and_history',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
