# Generated by Django 3.2.13 on 2022-05-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0012_auto_20220508_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_return_and_history',
            name='book_cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='individual_cover'),
        ),
    ]
