# Generated by Django 3.2.13 on 2022-05-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0014_book_maximum_no_of_borrowing_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='maximum_no_of_borrowing_days',
            field=models.PositiveIntegerField(max_length=1),
        ),
    ]
