# Generated by Django 3.2.13 on 2022-05-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0016_auto_20220509_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='maximum_no_of_borrowing_days',
            field=models.CharField(max_length=1),
        ),
    ]
