# Generated by Django 3.2.13 on 2022-05-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0018_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_pdf_file',
            field=models.FileField(default='test.pdf', upload_to='book_pdf_file'),
            preserve_default=False,
        ),
    ]
