# Generated by Django 3.2.13 on 2022-05-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0019_book_book_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_return_and_history',
            name='book_pdf_file',
            field=models.FileField(default='test.pdf', upload_to='book_pdf_file'),
            preserve_default=False,
        ),
    ]
