# Generated by Django 3.2.13 on 2022-05-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0020_book_return_and_history_book_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_return_and_history',
            name='no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
