# Generated by Django 3.2.13 on 2022-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0022_remove_book_return_and_history_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_return_and_history',
            name='workaround_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book_return_and_history',
            name='late_return',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
