# Generated by Django 3.2.13 on 2022-05-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0023_auto_20220511_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_return_and_history',
            name='workaround_date',
        ),
        migrations.AddField(
            model_name='book_return_and_history',
            name='borrowed_workaround_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book_return_and_history',
            name='expected_workaround_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
