# Generated by Django 3.2.13 on 2022-05-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0024_auto_20220511_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_return_and_history',
            name='date_borrowed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
