# Generated by Django 3.2.13 on 2022-05-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0025_alter_book_return_and_history_date_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='maximum_no_of_borrowing_days',
            field=models.CharField(max_length=50),
        ),
    ]
