# Generated by Django 3.2.13 on 2022-05-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ty', '0026_alter_book_maximum_no_of_borrowing_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrower_Record',
        ),
    ]
